# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8hOYeVZwLuOwvYWSDxwV7PZkHCxmJ7uOmgZmEdCNwOs=,iv:nN1f3Yfg1gDeMmxOwcEAeO2DfSN26S2L5odHuiX3n0w=,tag:wmDzQtHa2FYHvSBN8KXIYw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w8y0gm2r5n2c4fumn4e8hv27448g6qmh890nu7nwxamu6yy9upsq5dllmj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjltbjVPVzR5Q1VpdTBU
        RVkvVnJNbHNSUGd4OGtKdnRKQUsyNEt2Q3hvCnk0aVNLZVM0UHJRS05kY0paTEdv
        N2hhTzZkT29EMlRJQy9IdGV4VENYQVUKLS0tIE45MFpLUWp3NVNhT1VOeXRla1NU
        MFlVN21RYktwaE9XdFFFb0d3TmIwMUUKvFJIQNwCTPHBvp34BYhvOFxZmsmAKdWe
        C5GjEXIyebjmXCHcdhLavKeP1IUUDz607u0dAwVvMCS26ZTbaiblPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T00:41:57Z"
  mac: ENC[AES256_GCM,data:Z237JHDmEVbE3kDf3BjTqQEBgS6TJD3ZdPRoEHNe+ADIR1JBIKtp64Dpg+1mzh1Zf9+LDbCg3apVmwhVYORbIfUYJr+YFK83JlS6MMvLlUlMHBTfV1jLAmhDVLFE+n8WC21bmTbRWT3qG1WG94NtQT3v+1BfyEEpmRPsgpgQQz8=,iv:XCW0D8iBa21Rplu9MMI5uV2QA+H4+ZTObSADdH84hLs=,tag:3TUWZ+BUxdPLmWMIZysR1g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
