# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+wOA5UuMVeZbbV4iaU72SBpfn1a9r5UKqCjJenySUQ0=,iv:CqRegxq+4m+yX8dOsYclSCI70dYwpNRnVJH0jaGmyvw=,tag:emw1AUGvHI2+VqEz2PDi5w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUjJBalRSRUt4UXgreWs1
        VVlUbmtvTW5MUmw4ZTVDSnp1LzkyU2lISUZVCkpNRWErK25vSFdvT081eWNUaFFS
        dFJuS3U3QStTYTVMY2lWcXVZVFRTMm8KLS0tIHhuTUF1T3dFa2xRN3lwMzBBV2Vl
        dkxNdFVla1VmYkhhN1J1NFozeHEzV0UKtAwzNVNzyIZGE3P4mlYXHz8csENqL1ur
        vBGF8PvOSo4I7vhuFOQRN+hHGPTDymeWQ+rAWVb4e35AbuT72FSUJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T05:03:48Z"
  mac: ENC[AES256_GCM,data:SB8FmhjissuhqPbBqXtr0qGNfachod+IE6ig0nhS9zq8NpuYg0fvOqpdF3jkU+Kef4PcToe5rW6xwy/a3vEvewcDG3G1PYy8EbhybyiV7J0cTwiKTjAxsvxHLeQMQ4lXQIfR5i0whoHNfdkUOnMZxDjhQfyvzlad8OCyK2wsDqE=,iv:Lt7N5MTm2RTJ6x9KcPgA4wzMC1LIYWKmd6I5HDQ3ojs=,tag:NTPqYGxjIUHDvXgNq5Rbxg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
