# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:fGkyV/2Nfn+vwFHPlnuDRz2KQJsI9QWdD2anN7GTjYI3IQX9d0YCPTHPuC4=,iv:lxt/UZkSJv+udSeI0sVeWK30m4xNhFpr5XXxGwGueK0=,tag:BgKZ8gcyzS3rVppl0vrcIA==,type:str]
  credentials.json: ENC[AES256_GCM,data:VARV2Axwu6T0yMDKSpx0hu5SF/6DkvVtJt7MwgGXIKZCcSl+Pn2K9B9nSuVdQ/T5CPVjdB3Bm0Zjlk0T6na1lemC4Rx4A/WtU0+XqeOSNNnj1+6qh3I+aA8c8884T4KjqyXSvctRSHyyLksI8ncbpWqjmAjjd8RXanWnjuos2gnDPTiTO4fWSks9bmGWkIs6Py70E2kPg2gmrSI5WcbDseRCeyas0XT7xT9VPixPNo9pc1O1lDbX,iv:Y4TqTjb+TE4sILWUjb0QdNnrXbEy3dDgOf8TgiMJupg=,tag:ocPUhhp7Jxz0XqWfy9znlg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdTFpcDZYNlN4a2tOMHRE
        VFQvWkJ5L0lRa2hwVGtVODdxSENaaExjMGdFCnVTRWZiUWFuSytyZjh5eEdmY0hk
        YjRSZWZESE05cEpxWlN3T2FoSTRESVEKLS0tIEZpQitNd1V4SWh6ZCt0U2lWOUt5
        b0hEdEhqR3BkWmEyQUlmSFBLME5FVUUKF1LqowZA6pM6Hvz5plbUwmQ2C0AknQXJ
        VCYV3+Lan1AcTysoUP8WShlXpjq/w4s9BA9UL1v9vJs5N9RI4OP5aA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T04:15:20Z"
  mac: ENC[AES256_GCM,data:9Hi6CE9OFHjU/dshIeuVJzBFeZZi8YKLUDBuZwli7Hyq9UqhyEaHsEdKpW4i65zWr+CGo1DQPuuK+1m6PzrxAOc0mA3DMnATdJbrmWhPAl40jIkc1S0N6XFQy7QtgFCCKULfePtGIqCJSJD6f3f65//cFAM3J2SUvc5FOY13YaY=,iv:nBkKxZtDRtfInSypaGkr8Ps5Sqf5XtC8DS6uxhmxoss=,tag:h/FFwwJWk/rM8+Dnq6FodA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
