# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:sbDKNyNXY/3uRWcD/xJyOqhb71xV6i3i0m40ADuzMYHSxmyW,iv:nC2GNPnvFsEDlJ7mE6bnFonZaHNK8ORhtL0UHg+G9SA=,tag:5mCWgMm+TGr7MLRE1uUrsw==,type:str]
  credentials.json: ENC[AES256_GCM,data:WW8TYNy1WybN/KTMpTQFj61NQYj+sVC023tcL7KBb14+WIgqJiw6bY/lH8kytmIddP4XxTw4X1yv6lotY1qU9tWvQgm6+wDDo/3R3i9hFh/dNWi5iRw2zNXOmCd09CoXO5jGec591NhbDEZd3396xQU8MnI3si0SiCggBg8LtIyganOtppVkpHH6dk8qEBt2FmHoWgRF4SpuvamdieG3LxJRTffT0ieMMdWeIv/kXA==,iv:udvRIdF220DuxLcZ/eUCRQZk/IF8Pqq9ZwFG7OnbFE4=,tag:k95xIw8OKPSqfqhMSAm0/Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNmZVL1RsM1VMVGNOdG80
        bW83L3dONFJ1M3hYNHIzcVV3RkZoeTZDUnpzCnpOaytxZWNoV2YzUlh5SVlYMHB2
        N09DV2V4UjUzaGFrM3J1QWJHT29tS0kKLS0tIE5DSm9VRXF4d2FaYlhZTGgyVC9O
        Z00yUFdzMW1PWks5dkJkdzVLSGw1SEkKjm0pwH6M3gZieeMeWc8+bT8X/Zi+v509
        CVzAo4rMgeLSpoNQ+lxl96YZVNLpuW6zkpzyzBtFcTxpfOwyIV4Ylw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T22:49:40Z"
  mac: ENC[AES256_GCM,data:+xVN20oPekuiiizCBAwnoIkq3zlyr5QRE1fpCKAI8RiI+mhf0L2cfBpuWVDhIvn2jG8s0VmZoGyowubyU0hJEa/p18FNdL4JgoJQMaQ2tjgp3kln7lOOQRLc/gYESPm0VAud7ktAeBEIulrYBR+6dQtQaZfWNcbWUqpe2x82uvY=,iv:J8QRMSBWEX14QsCE/x8vvN+qFW6ixWaP3Ppv3Rh8qkI=,tag:uUY2mKJmd7FbnIWzGeqaJQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
