# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:KsNXpeH6B8e3RHWHnvVbU2mk7dEZK2WYdTp0DXj0wZDjnV2s,iv:w3PvHhqd4nArt3aM2AuEL6DuGw+XADi9k9Di71XmNZc=,tag:PsajaWT3B7+30D7fMH3ALg==,type:str]
  credentials.json: ENC[AES256_GCM,data:95FJIpH3GPmOd4/+gzbOUvnCO3zpdK2bdoNCga26/ZE1ZnVcSLo/zihAErw0qHE6wqbjycZOit3aEof5RO5/xjVlGSqqoHoNUmJ5aDT3+s92UsGYxZTsPpKnfK01VZBd6xXontrc77BxditQruko8kbzrqz/ykgKoQt2HvRck5lGZ1zs8aHcpqJU9hegFW7JZs1GoJY3DbcPjUv6hRo1/dV/K0Wtc4t43kG5foyUmg==,iv:7+mdgiaKQzZFbOXDo3vN7LAO4EhdT2dOtaFLQiluSDo=,tag:gZqFJ6IRQztFLYrLSHKpGQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVG4vWC90Uy9IUktpdjN2
        VmxFSTJwS2Q1bjdQM0J1WGgwaURncEkwc2dvCjgzNUpFK3dSUTJMbFhYWW9XeDRW
        S21oSXhkTFR3YWsvcXgxZTVrNzBuaEkKLS0tIDlBeTgwWEs3VkNtcDB2WlZYM3Z5
        WE8vTWhMNFRpV3dLR0crT0pnWGlVZ28Kc76cKkd81X/s8lmBdM85V6Kc2ddJrfF0
        wJCiwtMDSHE/Si5OOEv5QwNPYIvbfpJe03sQs6pvAcfQ0aYBb5lGVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T20:18:58Z"
  mac: ENC[AES256_GCM,data:H7WXzkXiZvan1RilAFrbvh/xOEh/HCvRn3ZD/b0aByI0ePsWcR/bDuyCWjOJM9/K1gvAOjTmkq6OUjJ9N9aLZcIob7UIWhoB7K+Oe9HGBis2YUP5zTniqas3/bJTQvlHISIKlK6IiAPi+Wati7mErBN+wDaPexHI+ZJIBhUSUck=,iv:Gl/sGUHSIcpQCwsmxlS+qg/tdjoeyztGIPsFnWkwElI=,tag:l9asY5/YR8enQNMEzK/olw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
