# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:0Oo7zBDSLHZ3FpgmCqjVOJRmI9vmkFhCvydluPXqCP6netbQ,iv:WtJnRLR1/0mQFNFBJPYmBukhlXoiTMO8nBSLrcMs/2g=,tag:hU+I6yDvaaEUdaBB7/FErg==,type:str]
  credentials.json: ENC[AES256_GCM,data:ZbrYZ++JqMzHLtvNuOjDTP7KKEE+eoca2zkHseJUhcGT2lEkH8NySUD+4PA+O1p4TOsG3B9iAxG8tVWks6O1dUc8E3nI2ftB6iR1dm43ya2EUVhwG9YbOm3d5II9PKoOsEskSVpY1mxwxEK+frLAH+Mcei5WswcRlCY1lzWHItPKxppCkMqeCQvENzh44m0TxpvxL+9VrZObziJX501+GGedYJlEG6GrFc2IN6f9Ow==,iv:S2IzCuOcs6p7Y1PjhH0bA7c5kZ08okbVqK9uYqNWDFg=,tag:CqQ66uUat1cq7Zks7JZOFg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w8y0gm2r5n2c4fumn4e8hv27448g6qmh890nu7nwxamu6yy9upsq5dllmj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraGVwelV3RlhUdWlCZHN1
        dGJIbzNzQmIyMXY1dlVkQ2drei8vWlRxTUdJCll5cmNXOU1hbUR4YTJ5VXhzcVJU
        eXFnQVFIZ1d1cGpZYUJDa0h6V2FYM1EKLS0tIEdpRWtEdndpQWttbDhwaVVvNCtn
        UFA0MGs4aFFpckIweTduT3pFT091ZVUKF1PgaEWVc4un5aKf2sqyeJNNVP5C2psh
        4WI46frQQFjEmRcJZ6QmidqxXhJYKcLrgInWhi2Dc8cPsdRx6gX7EA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-10T22:54:00Z"
  mac: ENC[AES256_GCM,data:YyiKRjc5m8swhrnWR7ykYStzAAhQgMSgoHwTl4kxL6DlZFtJT2hFaUeT2B7GW/Zr7ipw1lWOS1VugIn4z4KTHYDDg4qQE2AhPlLTd3dW/GURCSj2no/HciEdlKOOerIEkMxQHucQCJpSgLdoZcXTGkiCGE+XhWpKYqDF/gttnvg=,iv:DBNKCgSuUEXL65Yu2MhSlwvuQH0vI68u3GeiT0ksi+0=,tag:S5C7NcegbZCPS4b+bxSZkg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
