# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:B+F3kjg+PJZ6/DEBuGDm0X8pRNFnKBC3K2lpRs1qmXkACXBI,iv:1n5/1/tiFpoihdTviVWdLai5IoKMg00h/D3EhcTHhQA=,tag:sKocoqHkfYVamsUCPiGB9Q==,type:str]
  credentials.json: ENC[AES256_GCM,data:quA8fwREKIxa6ZfvJfiC3uuI9UfCalyZ86aIhZdvM6w8FtQQLy7oTOwoPZaflE2Xhyo6CjJ2Hx1EEH+TFhva7WrDAWoQ5/zmSF72SQTpmwsPzfN3UY0tFl41kShyP+9TRkXXG8PNtNa/NtQFGta6bJQi9Ojcc0xhC0fw9Y6KAJAUlQ9+MCUooAvCK4KMbJpq7hkjp2tujtLHGFeLQG+OYPCa8lp0wvb2VRWIdu8WWw==,iv:j2nZyVunHZp+Hxvlr4A9OIktlIdumwxuqaGvAd91/WY=,tag:U3A/PaduMHMeSh6uMj6C6A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOE5FVjExblN0WVpXN3l3
        MXdYNE1qZFpDdDVnbFhGZUI4NWEvR1lha25jCnpLSGg5VmNQazRQc3VrUVVsQWkx
        M2xiT1d2SkJMZThWSng1ZEhzR0RZQUEKLS0tIFI5cEFUbHVYdWFBTFdjWWJnb1dz
        Sk02TjRCUUZtZUMyeE92eE96OUlsd0UKEKsKO6UjJCFHvvQIHGCyPWbbsmFuiAhL
        H+mfBtQ2tGpajPANUpZ7iuEZMSSfDf+D+wCK5/y4zUWqf9p6VZUDzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T03:31:38Z"
  mac: ENC[AES256_GCM,data:KKyHnqSxJKHgI0W5dtwpgmgsnKEKrm4ofdC2Oe+nqPr30NM00/gdgm3rSb1SzUsms3z79LzlkRCtpWuUUUpqcXzVYSoUayx7zgEwWc+B72DRvI7JCxrWrNW0hWec/4E2fk0uehW9dlVkjvNayt4soZ/aP2+8Aq4ZUVBuTrJAHrE=,iv:ChBHrN3P7sKOadl2nJX9HTuotxCiUT/1jvbUC+SPayE=,tag:IxRw5Q3SNNmAeBKBdUkwiQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
