# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:grawGDn9bZ0N9syo,iv:d08sncf9F9gSOrNdfE8JhOKYKpDDeTOlUERVd68tocc=,tag:zpqMqJAEHXkQQfUkv48qRw==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NaibYIvC90tvPVTZlNK7MlPJJWtYpA==,iv:BZZy9528obwXh8CmCc9T0SSm3tbg2OzXJCs8r4LSYmU=,tag:ueQZ3gvpa00DLsDd1z211g==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:x8GJZmW1sgZ2t4A6djhM0VZUlAEK8IQT1FehSp+fjpzCH/iQ,iv:UANUW2X/kJe2QSwrFHDBIxgYNGyCsw5PEBdk8sBAQzM=,tag:NZf3psYxgIIsB8f3n3/Ing==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YjI4cTBiR0JpNVJhNy9y
        aVJFNEwyRHlNWGh6bzRRdWxlcTNuTmxBSXcwCkh1SVJVem9GeGo5V1RxalpYdEkz
        MXc4SGZJMERpdDZWQUNKWmlSMUhMMEEKLS0tIEtjMUM0UFlZTkpjTDFocnlweFlk
        cTEzRTduODJSYWFXRmM3QjhxSEhnRFUKmQKKf8aI64cTBVSqx65np1DI4S34amp1
        ksG67uUOimXM3ZRtjW8HSSGPIIpdeY4Bz8tbZlRe/jwFAJ7/614Gtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T00:00:04Z"
  mac: ENC[AES256_GCM,data:AA62rFbKr7LmCUCJ8kAgrGFsdWLqqdOPjMcescYAQbGTZqoUivvOk/uLW9nylSgOyG7/op4kuLOmKsMFsYrQPxOegD8MlbKnXm/Z5i5f7Xsycdo8x0Vl82SvaNPEWVgOCfijPOjt5x+DTUVpXQc2+FCpnEcZAiHgIZXKL+Widzs=,iv:SF0COWvLCagQtSd5D2yilwmCoOepXjmmmjsyFgQIid4=,tag:WhHe9lcdD8cGbYM2X+Ogwg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
