apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: '6.7.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  targetNamespace: podinfo
  install:
    createNamespace: true
  values:
    replicaCount: 2
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
            - path: /
              service:
                port: http
