apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: '6.7.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  targetNamespace: podinfo
  install:
    createNamespace: true
  values:
    ui:
      message: "HI"
    replicaCount: 2
    ingress:
      enabled: true
      className: "external"
      additionalLabels: {}
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: "podinfo.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                port: http
      tls:
        - secretName: podinfo-tls
          hosts:
            - "podinfo.${SECRET_DOMAIN}"
