---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      version: '6.7.x'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 1m0s
  releaseName: podinfo
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
      valuesKey: values.yaml
