# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nDy+FOKhDV/k5G9TRxP50+t3zBTLRvAxeV6QMfm8yrIxBeOS695irQ==,iv:3y1FuSeeG3STpFUt1CepHEQGYAkrw2j3DNclsXMwWSE=,tag:s7ba/JLh33xWnSHOfy7Zow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcDV6Kyt1TnRKdm9sMTZ0
        SVZMemYxRzNkbkZ0R3V4YUZFd3lkOXp1RFJvCkJ4NXY3TEVaV3k5WUlpL3BRY1BI
        MWNZeEVXNW9JTmJML0hncUZ0QW5zZVEKLS0tIEY0ZDNYaTFJK1grYUlwRXg1ZU1D
        YllqbzVjM3RrQTduVFhtMjZraXV4WWMKL6pT8FCRPmBwkQioHRZOXEPUyQQww9HX
        9O2w+5DIuQPm5wKhA9k7/jw9SIaTKdCWeXphj834ys66hHaVcTPuew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T05:03:48Z"
  mac: ENC[AES256_GCM,data:eJPcZYxyuD4MlS7q1yWZM6LNaqficqY2W2e/UXelqb3l374sJPdgcZKiFHGROeBsE0ZF1en5aeJO0veOn4nC1LD13e7vj4CXG5xjG1AjjUh0PuW6k3brUpRkGAoeKeTLz4Y8qNF7rPkBTikfm/9kw5tYu22DtVvb5s2JXoRHUlE=,iv:Pps/1xAJdm84FgEXOpSBup0S7NKswhYW+M8I9/jHNgc=,tag:EXdTUONgI9AizWZN/lU91w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
