# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:IZ44P+IK+2lJYNUftcCS4DQA4s4cr0xqtRBmVcBpZXiSFzitXGEFlw==,iv:SeEYOZtx7H9zHeuwT/JYeLwxeeLNz4BgeNw40y2eAIs=,tag:ymrzYKbMR3qnMJT0Jm5W4A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTWt6c0pCMUR6a2E0eVhi
        ZUlJZENBQkVYdXROSENwaWJhUVBXTm5MSkEwCmdmUkhRc1QzRlZXODBZWk1pVFZB
        NUJrOVNFVnYwNndvVkdEbmszTWlCTVEKLS0tIHVYcFdjNTEwWFZRUEd3dHk1TkZ6
        NEEybGZqVldZTzF2bXF4bUw0Qk1MNGcKTDmSWT1pLoJM/Nk8KPhM3XV1tAqr6XSi
        L0gdVgQsGT5/nE3ne8PrTc60PBNjBB/OxUeNYb/4kRmwSgSw0MGJBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-19T17:48:43Z"
  mac: ENC[AES256_GCM,data:FkQXVh1qJ8+g/nml2v+y4PLhTmO7/WJk40QmkDh3QIOG/ZM4x3kPn3T+akahCDuH6JGJ8ZAC5hgmuGkjz7ugqbUqGDh5/JoNqZmE9k3DUYiagHOvzvyjeydnXjfDKA11+Jkw2tqjHVeDPXgdCC3ihEUqgqhdf/BXjP4vQBAWRvk=,iv:O6tUONR56rN0pyS2/Qvxe3R/75YZQdXpA38/DmVqNJc=,tag:D+IHYcmh531cp5NTUXMP/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
