# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yWOSv3mj/O6l1ix05aUeCfZ6ZhuVZa7zLuSlgtrQVy6jEd1Xvrn8Cw==,iv:zqpoxpSh+QNnhgE+NCmsRn6MtIExvJA8Ok0/s9GVu7A=,tag:8/zOp1llAFgkZpFxdrgL+Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w8y0gm2r5n2c4fumn4e8hv27448g6qmh890nu7nwxamu6yy9upsq5dllmj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZnE1RHVyL1diWlBNS0JP
        UEREUHlsNUw5RTdvcGtJdi9Dem5oRGNNVTM0CkhmNzFXV3Z4NHNuWlRkdEx3ZjM1
        anJxMHZFR2tlZXZLYzdCY1pCRzc2UmsKLS0tIFpTM2FNM1FFcTNNVTVZalpFQUFU
        QU5mTmtQYmtnTklDUk51WGZiYlQyd1kKu9ePmA2veWvrGbeKpBbsPQh/vGn1wzMr
        XfZIw8Q4WLwsJ4U3KkSOJDG7mk2hqWd5N+xnQ+y8E9gTJWQ/5GOzwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-11T00:41:57Z"
  mac: ENC[AES256_GCM,data:67502ZhtHlLArWBha0+HXI85ANdIxEpXoi1CcXBvkapH/FltdoxwTqX4WAT11nYCVAYoxAzydSjWm7cRiTr+1VFahZ/3pMbWVy8nhm2+OkKtvOyxyzhkWdCbgek2mIzNtrED5u1PraxOn2ey1IN4yMl57iV4owPYqlv88UtF/eY=,iv:IkYQvJ3PU1eiKEVEi18Td4wq3h8FDKC4w560mLks1LI=,tag:EEPW8fEM83w56glVUM/EGw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
