# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nL/mEn/zgvM4P95IV2gf0qXnDk5j8MxuNV0lm95ObTDjdWWD7Heqhw==,iv:y5FNl3Aav/eDUPIjYggJWY0qgKpzT9ItbOtGeWuEmJU=,tag:Z6hHuzFAj/Q+46tdteraGA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWEY0eGZvTDVsR2JlUkFn
        bHA4dU54eXhRMTFDb2hESVI1UUduYUVkZ1VNCk5zOUZFMFNOWGN2cVF2WS9ETEdl
        bDVnWTNsUTduRUZKSi9EVU1rM2w2K2cKLS0tIDNSMWJQVi9pZ0tmRnRoaHNtdTBU
        eStyYVVSckFWeXB3KzVEQjNWUk91eEUKCNkeAME3ZsuEqpLXpuVSKsslgQ1S+Chw
        wevULTdXqnSb6aO4zWEMJbGAwzQld78zG1UhMpuwCl/clSq/TFL9Kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-21T02:53:11Z"
  mac: ENC[AES256_GCM,data:GR0oyH9Mw3gv4OSRz5pCVMdd8K1ALi3FQ2eFQzvK2glpOP81n3aQVHwTA11R3Pl2VoLAn3CGi43JPxGts4Hrt/Ll/GXc9BC445VmY9dAWi9ktE44I9uwmg+zb5ybUtC2Wz19zW8E2iUysXnOW+2hohXhN9n+u3YR4z7KrgKXehM=,iv:LA+j6pA4JNRerfdzXnoWEeO5MVAiFCHNvWpPRhT1fc4=,tag:5MQbKEfOCjm/KbRzwm+Bpw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
