# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ktzrqgcVvgNqmTkABtrIoyi4c7PLJaKZEwDc/lzU+SCHuCXCgVqSSw==,iv:kzisdO9M4Ixx/YrP5HHo0AzFwpy1HTOspuYPK2YbzUM=,tag:1wyhaNW7y42bGm8AsG6Hfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vzkvfwvx9z7jpvm938cwjpsdsgkf3f7rfxa3v2ha42t3gwn40chqqknd2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVkhjVmo0ME1aRm5kNFd5
        ajVqUkZYc2dUNktualAxZWgvMFZ4UWdXN3d3ClVVRFFlRXB2amgrSStYVmZvWEFC
        R2ZvK1VQQlY3SGQzbG1wOUhTcGk5OUUKLS0tIDBmNnY5S1l5dS8ra0VUQXNpbmcw
        V2hMRCtSWUpDeHNXSVpPT3NnWmtxNFEKNc/zaVUOCwFUNP7LKozzfXUBKQUNySyC
        mMQTKq3B/5UTbPVCSD581fta+psc4rMhjQZtJhyJrBv0yruBleQAng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-14T01:30:57Z"
  mac: ENC[AES256_GCM,data:i+M5XJn2Wb5n5AssKrDGAWfnoc5qzsl2pEN8ljUjurZPzz1XgTffqrpVDtPwiXRqPObAA8QIieR0xnZg4VBNh8IvQuq+dzowlXvqqt8Oe5ScPYNCgSV3Al6rkL/iBU5fHlRFgpxUx0hCOrsfM2wg9z8IA0HMwZRMSGdeIDIhAJM=,iv:Ei23934OZNipNG7VPO2wvMu5vu1fkbns3QWz6EX0Hgk=,tag:X9Mx5/au89LbTPdekUQM0g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
